name: Test

on:
  push:
    branches:    
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test-sqlmap:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: sqlmap
  test-wordlists:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: wordlists
  test-trufflehog:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: trufflehog
  test-ffuf:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: ffuf
  test-postman:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: postman
  test-zap:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: zap
  test-burpsuite:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: burpsuite
  test-nikto:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: nikto
  test-musashi:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: musashi
  test-juice-shop:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: juice-shop
  test-ssrf:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: ssrf
  test-vapi:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: vapi
  test-dvwa:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: dvwa
  test-samurai-dojo:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: samurai-dojo
  test-wrongsecrets:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: wrongsecrets
  test-dvga:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: dvga
  test-k8s-labs:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: k8s-labs
  test-amoksecurity:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: amoksecurity
  test-wayfarer:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: wayfarer
  test-plugin-labs:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: plugin-labs
  test-mutillidae:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: mutillidae
  test-katana:
    uses: ./.github/workflows/package-test.yaml
    with:
      package-name: katana
